---
function_keys:
  CAIXA_TIMERPIX: 10
  CONTROLACREDITOCLIENTES: 1
  NAOPROMOCAOVENDAPRAZO: 0
  NFCE_SERIENFCE: 104
  NFCE_SOLICITAIMPRESSAONFCE: 1
  NFPAULISTA_HABILITADO: 0
  OPCOES_BAIXACREDIARIO: 1
  OPCOES_BLOQUEARDESCONTOPROMOCAO: 1
  OPCOES_IMPRESSAOPIX: 1
  OPCOES_IMPRIMEDAV: 1
  OPCOES_PROMOFINALIZADORAS: 1
  OPCOES_RECEBIMENTOCARTAOTAXAACR: 0
  OPCOES_SANGRIAOBSERVACAO: 0
  OPCOES_SOLICITAOBSERVACAOVENDA: 0
  TABELA_PRECO_TROCA_VALORES: null
  TROCA_VALORES_CASO_TOTAL_MAIOR: 0
  VALORMINIMOSANGRIAPDV: 0.0
  VALOR_PARA_TROCA_VALORES: 0.0
keyboard_keys:
  TECLADO_ABREGAVETA: 113
  TECLADO_ACRESCIMO: 0
  TECLADO_ACRESCIMOGERAL: null
  TECLADO_ADICIONALGELADO: 0
  TECLADO_AJUSTATELA: 122
  TECLADO_AUTENTICACAO: 90
  TECLADO_BAIXACREDIARIO: 71
  TECLADO_BALANCA: 33
  TECLADO_BUSCA: 16
  TECLADO_CANCELACUPOM: 123
  TECLADO_CANCELAFUNCAO: 27
  TECLADO_CANCELAITEM: 120
  TECLADO_CARTAOFIDELIDADE: 69
  TECLADO_CONSULTACREDITO: 121
  TECLADO_CONSULTAPRECO: 116
  TECLADO_CPFBIOMETRIA: 0
  TECLADO_CPFNF: 89
  TECLADO_CPFPINPAD: 0
  TECLADO_CUPOMDESCONTO: 0
  TECLADO_DESCONTO: 90
  TECLADO_DESCONTOGERAL: null
  TECLADO_FIN01: 68
  TECLADO_FIN02: 67
  TECLADO_FIN03: 80
  TECLADO_FIN04: 75
  TECLADO_FIN05: 83
  TECLADO_FIN06: 84
  TECLADO_FIN07: 70
  TECLADO_FIN08: 78
  TECLADO_FIN09: 81
  TECLADO_IMPORTACONDICIONAL: 67
  TECLADO_IMPORTAORCAMENTO: 65
  TECLADO_ITEMGERAL: 112
  TECLADO_MENU: 122
  TECLADO_MENUFISCAL: 119
  TECLADO_MSG_NO: 50
  TECLADO_MSG_YES: 49
  TECLADO_PAUSASISTEMA: 115
  TECLADO_QUANTIDADE: 81
  TECLADO_RECARGACELULAR: 0
  TECLADO_RECUPERAVENDAESPERA: 109
  TECLADO_SANGRIA: 0
  TECLADO_SISTEMA: null
  TECLADO_SUBTOTAL: 32
  TECLADO_TABELAPRODUTOS: 117
  TECLADO_TABELAPRODUTOS02: 0
  TECLADO_TABELAPRODUTOS03: 0
  TECLADO_TABELAPRODUTOS04: 0
  TECLADO_TABELAPRODUTOS05: 0
  TECLADO_TABELAPRODUTOS_SUB: 0
  TECLADO_TABELAPRODUTOS_SUB02: 0
  TECLADO_TABELAPRODUTOS_SUB03: 0
  TECLADO_TABELAPRODUTOS_SUB04: 0
  TECLADO_TABELAPRODUTOS_SUB05: 0
  TECLADO_TAXAENTREGA: 85
  TECLADO_TROCAOPERADOR: 118
  TECLADO_VASILHAME: 86
  TECLADO_VENDAESPERA: 107
...
